# vi: set ft=toml ts=2 sw=2 sts=0 sr et si tw=0 fdm=manual:

# Don't print a new line at the start of the prompt
add_newline = false
scan_timeout = 10
command_timeout = 100

[battery]
disabled = true

[character]
success_symbol = '[#](bold bright-blue)'
error_symbol = '[#](bold red)'
vicmd_symbol = '[#](bold green)'

[cmd_duration]
style = "bold green"

[container]
style = "bold cyan dimmed"
format = "[$symbol ]($style)"

[git_branch]
disabled = false

[git_commit]
disabled = false
commit_hash_length = 7

[git_metrics]
disabled = false

[git_state]
disabled = false

[git_status]
disabled = false

[jobs]
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true

[nodejs]
disabled = true

[package]
disabled = false

[shlvl]
disabled = false
threshold = 2
format = "[$shlvl]($style) "

[status]
disabled = false
style = "fg:red dimmed"
symbol = "âœ–"
format = "[\\[$symbol \\($status\\)\\]]($style) "

[sudo]
disabled = true

[time]
disabled = true

[username]
style_root = "bold red"
style_user = "bold green"
show_always = false